#General Jekyll Config
highlighter: rogue
name: Rapida
description: Sistemas Academicos
url: "http://clcmo.github.io/rapida"
lsi: false

#Setings
permalink: pretty
#theme: bulma-clean-theme
remote_theme: chrisrhymes/bulma-clean-theme
theme: jekyll-theme-minimal