#General Jekyll Config
highlighter: rogue
name: Rapida
description: Sistemas Academicos
url: "http://clcmo.github.io/rapida"
lsi: false

#Setings
permalink: pretty
theme: bulma-clean-theme

defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      author: "Author Name"
      layout: post
      hero_image: /path/to/hero-image.jpg
      show_sidebar: true

      ---
---
$primary: #333333;
// Import Main CSS file from theme
@import "main";