title: mPDF Manual

description: mPDF is a PHP library which generates PDF files from UTF-8 encoded HTML. It is based on FPDF and HTML2FPDF, with a number of enhancements.

baseurl: '' # the subpath of your site, e.g. /blog

url: 'https://mpdf.github.io' # the base hostname & protocol for your site

github_username: mpdf

# Build settings
markdown: kramdown

highlighter: rouge

redcarpet:
    extensions: ['no_intra_emphasis', 'tables', 'autolink']

kramdown:
    auto_ids:       true
    footnote_nr:    1
    header_offset:  1
    entity_output:  as_char
    smart_quotes:   lsquo,rsquo,ldquo,rdquo
    input:          GFM
    hard_wrap:      false
